n = input('Digite algo ')
print('O tipo é ', type(n))
print('É alfanumérico? ', n.isalnum())
print('É alfabético ', n.isalpha())
print('É numérico? ', n.isnumeric())
print('É decimal? ', n.isdecimal())
print('É minúculo? ', n.islower())
print('É capitalizada? ', n.istitle())
print('É vazio? ', n.isspace())
